# Test.create(created_at: Time.now)
# QuestionType.create(name: "insurance")
# question_02 = Test.last.questions.create(created_at: Time.now, question_type_id: QuestionType.last.id, text: "Какие негативные ассоциации у вас со страхованием?")
# question_02.answers.create(created_at: Time.now, value: "Трата денег", is_true: false)
# Answer.last.answer_results.create(created_at: Time.now)
# question_02.answers.create(created_at: Time.now, value: "Недоверие к компании", is_true: true)
# Answer.last.answer_results.create(created_at: Time.now)
# question_02.answers.create(created_at: Time.now, value: "Сложность получения выплат", is_true: false)
# Answer.last.answer_results.create(created_at: Time.now)

Category.create(id:1, name: "1. Электро-установочные изделия.", parent_id: 0)
Category.create(id:2, name: "01  Розетки пр-ва Белоруссии.", parent_id: 1)
Category.create(id:3, name: "02  Розетки и выкл. бр/защ.", parent_id: 1)
Category.create(id:4, name: "03  Тест больших данных", parent_id: 1)

Product.create(created_at: Time.now, code: "07315", name: "Блок С.У. выкл.2-й +1-й +  роз. ЕВРО 3В-РЦ-651   20шт/уп", price: 187.92, category_id: 2)
Product.create(created_at: Time.now, code: "07316", name: "Роз. 1-я. О.У. ЕВРО РА10-209   80шт/уп", price: 34.20, category_id: 2)
Product.create(created_at: Time.now, code: "05407", name: "Роз. 1-я. О.У. ЕВРО РА16-004  (307) (120шт.)", price: 21.12, category_id: 2)
Product.create(created_at: Time.now, code: "00633", name: "Роз. 1-я. О.У. РА10-002 или (308)   (256шт)", price: 13.56, category_id: 2)
Product.create(created_at: Time.now, code: "07317", name: "Роз. 1-я. О.У. РА10-212  (110шт)", price: 28.97, category_id: 2)
# Product.create(created_at: Time.now, code: "03993".to_i(10).to_s(8), name: "Выкл. 1-й  О.У. брызго/защ. А14-100", price: 49.20, category_id: 3)
Product.create(created_at: Time.now, code: "03993", name: "Выкл. 1-й  О.У. брызго/защ. А14-100", price: 49.20, category_id: 3)
